module(
    name = "linux_bzl_aya_e2e",
    version = "0.0.0",
)

bazel_dep(name = "aya", version = "0.0.0")
bazel_dep(name = "linux.bzl", version = "0.1.0")
bazel_dep(name = "llvm", version = "0.8.14")
bazel_dep(name = "rules_rs", version = "0.0.99")

# Remove after rules_rs 0.0.99 is published.
archive_override(
    module_name = "rules_rs",
    integrity = "sha256-w0arAyr5SW3fTNyF/Mp6TcNYgaIjalGzsImTkvgzuio=",
    strip_prefix = "rules_rs-6c45c1c32c3cab40eb69443ffc4eb6be9b4a573b",
    urls = ["https://github.com/fionera/rules_rs/archive/6c45c1c32c3cab40eb69443ffc4eb6be9b4a573b.tar.gz"],
)

archive_override(
    module_name = "aya",
    integrity = "sha256-fSFEIuD1VE7ILcmda66J+au+TMNFsA5iXdJNoqMm2Jc=",
    patch_strip = 1,
    patches = ["//patches:aya_linux_bzl_api.patch"],
    strip_prefix = "aya-9e943b24ca2256eecce7db73de43c8d2b49c0c33",
    urls = ["https://github.com/aya-rs/aya/archive/9e943b24ca2256eecce7db73de43c8d2b49c0c33.tar.gz"],
)

local_path_override(
    module_name = "linux.bzl",
    path = "..",
)

rules_rust = use_extension("@rules_rs//rs:rules_rust.bzl", "rules_rust")
use_repo(rules_rust, "rules_rust")

toolchains = use_extension(
    "@rules_rs//rs/toolchains:module_extension.bzl",
    "toolchains",
)
use_repo(toolchains, "default_rust_toolchains")

register_toolchains("@default_rust_toolchains//:all")
